In [1]:
from PIL import Image
import cv2

In [8]:
def jpg2png(path):
    jpg_file = f"{path}.jpg"
    png_file = f"{path}.png"
    image = Image.open(jpg_file)
    image.save(png_file, "PNG")

    print("変換完了")

In [26]:
path_o = "data/example/room2/O"
path_r = "data/example/room2/R"

In [11]:
jpg2png(path_o)
jpg2png(path_r)

変換完了
変換完了


In [32]:
def resize_image(input_path, output_path, new_size):
    # 画像を開く
    with Image.open(input_path) as img:
        # 画像をリサイズ
        resized_img = img.resize(new_size)
        
        # リサイズした画像を保存
        resized_img.save(output_path)

In [33]:
size = (4096, 2048)
resize_image(f"{path_o}.png", f"{path_o[:-1]}4096/O.png", size)
resize_image(f"{path_r}.png", f"{path_r[:-1]}4096/R.png", size)

In [34]:
size = (2048, 1024)
resize_image(f"{path_o}.png", f"{path_o[:-1]}2048/O.png", size)
resize_image(f"{path_r}.png", f"{path_r[:-1]}2048/R.png", size)

In [35]:
size = (1024, 512)
resize_image(f"{path_o}.png", f"{path_o[:-1]}1024/O.png", size)
resize_image(f"{path_r}.png", f"{path_r[:-1]}1024/R.png", size)

In [36]:
size = (512, 256)
resize_image(f"{path_o}.png", f"{path_o[:-1]}512/O.png", size)
resize_image(f"{path_r}.png", f"{path_r[:-1]}512/R.png", size)

In [2]:
def show_frame_at(video_path, frame_number):
    """
    特定のフレーム番号でビデオのフレームを表示します。
    :param video_path: ビデオファイルへのパス
    :param frame_number: 表示するフレームの番号
    """
    # 動画ファイルを開く
    video_capture = cv2.VideoCapture(video_path)
    
    # 特定のフレームに移動
    video_capture.set(cv2.CAP_PROP_POS_FRAMES, frame_number)
    
    # フレームを読み込む
    ret, frame = video_capture.read()
    
    if not ret:
        print("フレームが見つかりません。")
        video_capture.release()
        return
    
    # フレームを表示
    resized_frame = cv2.resize(frame, (1024, 512))
    cv2.imshow("Frame", resized_frame)
    cv2.waitKey(0)
    cv2.destroyAllWindows()
    
    # メモリを解放し、ファイルを閉じる
    video_capture.release()

In [20]:
scene = "Calibration"
pose = "pose_test"

In [5]:
frame_number_o = 61  # 表示したいフレーム番号 182
video_path = f"./data/data_real/{scene}/{pose}/O_raw.mp4"
show_frame_at(video_path, frame_number_o)

In [7]:
frame_number_r = 59  # 表示したいフレーム番号 271
video_path = f"./data/data_real/{scene}/{pose}/R_raw.mp4"
show_frame_at(video_path, frame_number_r)

In [8]:
def extract_frame(video_path, output_path, frame_number):
    # 動画を読み込む
    cap = cv2.VideoCapture(video_path)
    
    # 動画のフレーム数を取得
    total_frames = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))
    
    # 指定されたフレーム番号が動画のフレーム数を超えていないかチェック
    if frame_number >= total_frames:
        print("指定されたフレーム番号は動画のフレーム数を超えています。")
        cap.release()
        return
    
    # 指定されたフレーム番号にセット
    cap.set(cv2.CAP_PROP_POS_FRAMES, frame_number)
    
    # フレームを読み込む
    ret, frame = cap.read()
    
    # 読み込みに成功した場合、画像を保存
    if ret:
        cv2.imwrite(output_path, frame)
        print("画像を保存しました。")
    else:
        print("指定されたフレームの読み込みに失敗しました。")
    
    # キャプチャをリリース
    cap.release()

In [25]:
output_path_o =  "./data/example/room2/O.png"
output_path_r =  "./data/example/room2/R.png"
extract_frame(video_path, output_path_o, frame_number_o)
extract_frame(video_path, output_path_r, frame_number_r)

画像を保存しました。
画像を保存しました。


In [9]:
from moviepy.editor import VideoFileClip

def trim_video(video_path, output_path, start_frame):
    """
    指定されたフレームから動画をトリミングして、新しいファイルとして保存する関数。

    Parameters:
    video_path (str): 入力動画のファイルパス。
    output_path (str): トリミングされた動画の保存先のファイルパス。
    start_frame (int): トリミングを開始するフレーム番号。
    """
    # VideoFileClipオブジェクトを作成して動画を読み込む
    clip = VideoFileClip(video_path)

    fps = clip.fps

    # フレームレートがNoneの場合、デフォルト値を設定
    if fps is None:
        fps = 30  # 一般的なフレームレート

    # 開始時間（秒）を計算
    start_time = start_frame / fps

    # トリミングされたクリップを作成
    trimmed_clip = clip.subclip(start_time)

    # 新しいファイルとして保存
    trimmed_clip.write_videofile(output_path)

In [10]:
# 使用例
video_path = f"./data/data_real/{scene}/{pose}/O_raw.mp4"
output_path = f"./data/data_real/{scene}/{pose}/O.mp4" # 出力したい動画の保存先パス
trim_video(video_path, output_path, frame_number_o)

Moviepy - Building video ./data/data_real/Calibration/pose_test/O.mp4.
MoviePy - Writing audio in OTEMP_MPY_wvf_snd.mp3


MoviePy - Done.
Moviepy - Writing video ./data/data_real/Calibration/pose_test/O.mp4



Moviepy - Done !
Moviepy - video ready ./data/data_real/Calibration/pose_test/O.mp4


In [11]:
# 使用例
video_path = f"./data/data_real/{scene}/{pose}/R_raw.mp4"
output_path = f"./data/data_real/{scene}/{pose}/R.mp4" # 出力したい動画の保存先パス
trim_video(video_path, output_path, frame_number_r)

Moviepy - Building video ./data/data_real/Calibration/pose_test/R.mp4.
MoviePy - Writing audio in RTEMP_MPY_wvf_snd.mp3


MoviePy - Done.
Moviepy - Writing video ./data/data_real/Calibration/pose_test/R.mp4



Moviepy - Done !
Moviepy - video ready ./data/data_real/Calibration/pose_test/R.mp4


In [22]:
import os

In [23]:
# movie to images
def extract_frames(video_path, output_path, frame_interval, name):
    # resolution
    resolution = (1024, 512)
    # 動画ファイルを開く
    video_capture = cv2.VideoCapture(video_path)
    
    # フレームカウンタを初期化
    frame_count = 0
    
    while True:
        # フレームを読み込む
        ret, frame = video_capture.read()
        
        # フレームが正常に読み込まれなかった場合、ループを終了
        if not ret:
            break
        
        # フレームカウンタが指定したフレーム間隔の倍数のときに画像を保存
        if frame_count % frame_interval == 0:
            resized_frame = cv2.resize(frame, resolution)
            output_foldername = f"{output_path}/{frame_count//frame_interval}"
            if not os.path.exists(output_foldername):
                os.makedirs(output_foldername)
            output_filename = f"{output_foldername}/{name}.png"
            #cv2.imwrite(output_filename, frame)
            cv2.imwrite(output_filename, resized_frame)
        
        # フレームカウンタをインクリメント
        if frame_count // frame_interval >=99:
            break
        frame_count += 1
    # メモリを解放し、ファイルを閉じる
    video_capture.release()
    cv2.destroyAllWindows()

In [24]:
video_path = f"./data/data_real/{scene}/{pose}/O.mp4"
output_path = f"./data/data_real/{scene}/{pose}"    # 出力画像の保存先ディレクトリパス
frame_interval = 5
extract_frames(video_path, output_path, frame_interval, "O")

In [25]:
video_path = f"./data/data_real/{scene}/{pose}/R.mp4"
output_path = f"./data/data_real/{scene}/{pose}"    # 出力画像の保存先ディレクトリパス
frame_interval = 5
extract_frames(video_path, output_path, frame_interval, "R")

In [38]:
import numpy as np

# 'R.npy'ファイルを読み込む
data = np.load('./data/data_100/Classroom/0/R.npy')

# 読み込んだデータを表示する
print(data)

[[ 0.75704225  0.48070549 -0.4425034 ]
 [-0.08842974  0.74642044  0.65957313]
 [ 0.64735401 -0.46019426  0.60758047]]


In [15]:
import numpy as np

In [16]:
#Kalibr output to npy

In [177]:
def quaternion_to_rotation_matrix(q):
    # Normalize quaternion
    q = q / np.linalg.norm(q)
    a, b, c, d = q
    R = np.array([
        [1 - 2*c**2 - 2*d**2, 2*b*c - 2*a*d, 2*b*d + 2*a*c],
        [2*b*c + 2*a*d, 1 - 2*b**2 - 2*d**2, 2*c*d - 2*a*b],
        [2*b*d - 2*a*c, 2*c*d + 2*a*b, 1 - 2*b**2 - 2*c**2]
    ])
    return R

In [178]:
q = [-0.32801302, -0.33896052, 0.10159295, 0.87589503] 
t = [ 0.27359878, 0.0336999, -0.35338568]
q = [-q[3], q[2], q[0], q[1]]
t = [-t[2], -t[0], -t[1]]

In [179]:
base_path = "./data/data_real/"
R = quaternion_to_rotation_matrix(q)
T = t/np.linalg.norm(t)
print(R)
print(T)
np.save(f'{base_path}R.npy', R)
np.save(f'{base_path}T.npy', T)

[[ 0.55502645 -0.66043529  0.50573795]
 [ 0.52714005  0.74956928  0.40033645]
 [-0.64348194  0.04439741  0.76417266]]
[ 0.78847462 -0.61045397 -0.07519126]


In [180]:
q = [ 0.05933311, -0.07535888, 0.00028453, 0.99538964] 
t = [ 0.43209423, -0.00641689, -0.0104084 ] 
q = [-q[3], q[2], q[0], q[1]]
t = [-t[2], -t[0], -t[1]]

In [181]:
base_path = "./data/data_real/"
R = quaternion_to_rotation_matrix(q)
T = t/np.linalg.norm(t)
print(R)
print(T)
np.save(f'{base_path}R.npy', R)
np.save(f'{base_path}T.npy', T)

[[ 0.98160124 -0.14998913 -0.11816201]
 [ 0.15005666  0.98864192 -0.00837612]
 [ 0.11807624 -0.00950899  0.992959  ]]
[ 0.02407863 -0.99959985  0.01484473]
